version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: portfolio
    container_name: portfolio-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      portfolio:
  nginx:
    image: nginx:1.17-alpine
    container_name: portfolio-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      portfolio:
networks:
  portfolio:
    driver: bridge
